### ISSUE TITLE
Javnost, slika in šumniki

### ISSUE THREAD

**Issue by pdurcik** [pdurcik/Baza-clanstva-RDR#4]
Težave imava s sledečimi stvarmi:
1. Kako se določi uporabniku `javnost` dovoljenje da lahko spreminja podatke v bazi?
2. V `indexstars.html` in `uvodna_stran.html` noče prikazat slike `RDRgrb.png`.
3. Če se želimo registrirati po postopku, ki je opisan v `README.md`, nam delajo šumniki težave.

Nama lahko prosim pomagate, kako bi se rešila teh težav?

Ko odpraviva zgornje težave pa bi bil najin projekt pripravljen za pregled.

**Comment by inesmersak** [comment]
1. Za začetek mora `javnost` imeti pravico za connect na vajino bazo, verjetno pa želita dovoliti tudi select na vseh tabelah v shemi public:
```sql
GRANT CONNECT ON DATABASE sem2018_imep TO javnost;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO javnost;
```
Potem pa npr. ker podpirata registracijo, verjetno želita tudi dovoliti INSERT na tabeli `oseba`. (Sama razmislita, katere pravice potrebuje `javnost` na kateri tabeli glede na to, kaj bo navaden uporabnik lahko počel v vajini aplikaciji). Torej, kako uporabniku `javnost` dovoliti recimo INSERT na neki tabeli `oseba`: 
```sql
GRANT INSERT ON oseba TO javnost;
```
Pomagata si lahko s [PostgreSQL dokumentacijo](https://www.postgresql.org/docs/9.0/static/sql-grant.html).

2. Slike so static file: najbolje, da v folderju `static` naredita folder `img`, kamor shranjujeta vse slike, ki jh bosta vključila v aplikacijo. Potem sliko vključita takole:
```html
<img src="/static/img/RDRgrb.jpg" ...>
```
(kjer tropičje predstavlja še vse ostale atribute, ki jih želita nastaviti). 
Na temu linku bo server res serviral vajino sliko (ali karkoli drugega (v katerikoli podmapi) mape static) zaradi tega dela vajine kode:
https://github.com/pdurcik/Baza-clanstva-RDR/blob/5e67d8d1d6324625f20623354a8a876e3eac02ef/glavni_program.py#L63-L67

3. Kje točno vama šumniki delajo težave? Ko podatke spravita v bazo / jih jemljeta iz baze? Ali že pri sami komunikaciji, ko uporabnik stisne _dodaj_ na obrazcu? Ali vama delajo težave vsi stolpci ali samo kakšen, npr. samo email?
Če vama težave dela baza, tega ne bom mogla debugirati, dokler ne nastavita pravice uporabniku `javnost` na bazi.

**Comment by pdurcik** [comment]
Ko starš ali admin dodaja nove osebe v bazo delajo šumniki vredu, razen pri emailu (vendar to je najbrž zaradi polja tipa `email` - to me ne moti). Ko pa želim nato registrirati novega uporabnika s šumniki pa uporabnika s temi podatki ne zazna v bazi.

**Comment by inesmersak** [comment]
Namesto 
https://github.com/pdurcik/Baza-clanstva-RDR/blob/d3b71ebb7c510aafe760c26c3f6c448399bfc885/glavni_program.py#L136-L139
uporabljajte raje
```python
username = bottle.request.forms.username
name = bottle.request.forms.name
...
```
saj tako bottle prav prebere UTF-8 characterje. Podobno uporabljajta tudi pri `password` in `confirmpassword` fieldu na tej strani, potem ne bi smelo biti več težav tudi s šumniki v geslu. 

Poleg tega sem opazila, da v folderju _views_ v vsaki html datoteki ponavljate ogrodje spletne strani (header, footer, menu ...). To je slabo, saj je treba npr. neko spremembo v headerju narediti v petih datotekah namesto samo v eni. Temu se lahko izogneta, če uporabljata [`rebase`](https://bottlepy.org/docs/dev/stpl.html#stpl.rebase), nekaj več napotkov (da se ne ponavljam) lahko dobita tukaj: MolanM/Fake_wizard_productions#2. Bottlov template engine podpira tudi python kodo znotraj templatea ([link](https://bottlepy.org/docs/dev/stpl.html#embedded-python-code)), s pomočjo tega in podanih template variablov pri rebaseu lahko za nekatere podstrani npr. skrijeta menu, za nekatere pa ga prikažeta.

**Comment by pdurcik** [comment]
Težav s šumniki ni več, prav tako pa sem uredil kodo z `rebase`.
Misliva, da je projekt sedaj pripravljen za oddajo zato prosiva, da ga pregledate.

**Comment by inesmersak** [comment]
- V `views/uvodna_stran.html`, sectionu _Datumi prihajajočih akcij_, imata zraven vsake akcije vključeno sliko, primer:
https://github.com/pdurcik/Baza-clanstva-RDR/blob/cad89822ce163ac39ac6d0bf91a66e60c9b1482b/views/uvodna_stran.html#L20
Teh slik ni nikjer na repozitoriju (in tudi link do slik je verjetno napačen, saj bi moral biti `static/...`). 
- Seznam vodov ima zraven napisano starost. Ko pa kot admin dodajam otroka, je ta lahko dodan v vod ne glede na to, katero letnico rojstva sem vnesla -- je to željeno obnašanje? Bolj smotrno bi se mi zdelo, da otroka aplikacija kar sama razvrsti v vod glede na letnico rojstva, če pa letnica nakazuje, da je oseba odrasla, pa vrže neko opozorilo / napako.
- Brisanje osebe: za izbris osebe mora admin vnesti ime, priimek, rojstni datum in naslov osebe. Vendar pa sodeč po vajini bazi te 4 informacije ne določajo nujno ene same osebe. Edini podatek, ki unikatno določa neko osebo, je ID. Povsod, kjer imata brisanje, bi bilo bolje, če uporabita kakšen drug input element, npr. [`select`](https://www.w3schools.com/tags/tag_select.asp), ki naredi dropdown meni -- vsaka oseba je potem en `option`, `value` je id osebe, med tage pa lahko napišeta ID, ime, priimek osebe, rojstni datum ... pač dovolj, da bo admin prepoznal osebo, ki jo želi pobrisat. Podobno torej velja tudi za izbris akcije in voda. 
- Glede na to, da je pri dodajanju osebe field _funkcija_  tipa `select`, torej dopuščata le končno možno število funkcij, bi bilo smotrno, da je podobno tudi pri spreminjanju funkcije osebe. Pri tem bi bilo ponovno bolje, da bi namesto vpisa podatkov o osebi bil `select` field. 
- Podobno pri dodajanju relacije starš otrok: trenutno admina posebej opozorita, da morata biti obe osebi vpisani -- torej mu raje ponudita le osebe, ki so lahko starši, v enem `select` inputu, in samo osebe, ki so lahko otroci, v drugem `select` inputu.
- Ko v sectionu `Išči` iščem neko osebo, izpišem nek vod ali akcijo, se eno sekcijo bolj dol, pri otrocih, ki še niso plačali članarine, izpiše veliko več oseb (niso le otroci, temveč tudi starši, neaktivni, ... -- mislim, da se izpišejo vse osebe). 
- Pri nekaterih actionih (npr. pri dodajanju relacije starš otrok, kjer nimamo izpisane tabele relacij, kot imamo pri vodih recimo izpisano tabelo vodov) uporabniku manjka malo povratnih informacij, ali je action uspel in zakaj (ne).
- Ko dodam neko akcijo, ta na prvi strani "izpodrine" najstarejšo vpisano akcijo. Smiselno bi bilo, da za prihajajoče akcije naredita SELECT po vseh akcijah in jih razvrstita po datumu, potem pa prikažeta npr. prve tri (ki se še bodo zgodile glede na datum). Starš pa bi verjetno moral imeti možnost otroka prijaviti na vse akcije, ki se bodo zgodile (tukaj prikažita 3 akcije na vrstico).
- Ko izbrišem neko osebo, ki je starš, se pobriše tudi njen uporabniški račun (kar je prav). Bi se moral v tem primeru izbrisati tudi vsak otrok te osebe, če nima nobenega druga starša v bazi?
- V datoteki `pomozne_funkcije.py` na nekaj mestih vstavljata podatke na nevaren način: 
https://github.com/pdurcik/Baza-clanstva-RDR/blob/cad89822ce163ac39ac6d0bf91a66e60c9b1482b/pomozne_funkcije.py#L21-L23
To naredi vajino aplikacijo ranljivo za [SQL injection](http://initd.org/psycopg/docs/usage.html#sql-injection). 
Namesto tega uporabita:
```python
cur.execute("""DROP TABLE %s;""", tabela[0])
```
- Vidim, da uporabljata salted hash za kriptiranje cookiejev. Trenutno je vajin salt (`secret`) viden vsem prek vajinega repozitorja, kar je za potrebe tega projekta ok. V vednost, v produkciji bi se to naredilo tako, da nastaviš [environment variable](https://en.wikipedia.org/wiki/Environment_variable), kamor zapišeš svoj salt, potem pa v pythonu "uvoziš" iz environmenta prek `os.environ`. S tem v kodi ni nobenih podatkov o saltu.
- Zdi se mi, da je ta koda:
https://github.com/pdurcik/Baza-clanstva-RDR/blob/cad89822ce163ac39ac6d0bf91a66e60c9b1482b/glavni_program.py#L68-L76
nepotrebna, saj jo povozita z:
https://github.com/pdurcik/Baza-clanstva-RDR/blob/cad89822ce163ac39ac6d0bf91a66e60c9b1482b/glavni_program.py#L78-L82
- Trenutno pri izbrisu npr. neke osebe ročno brišeta vrstice v drugih tabelah (npr. _otroci_), ki vsebujejo to osebo. Za to se lahko poskrbi tudi avtomatično, in sicer, če pri tujem ključu (ki npr. referenca osebo) v tabeli A dodamo `ON DELETE CASCADE`, se bo ob izbrisu osebe X izbrisala vsaka vrstica tabele A, ki vsebuje osebo X kot tuji ključ. (Daljša razlaga: [Postgres dokumentacija, glej 5.3.5. Foreign Keys](https://www.postgresql.org/docs/9.5/static/ddl-constraints.html).)

**Comment by pdurcik** [comment]
Sem upošteval nasvete in popravil kar je opisano v zgornjih točkah, s tem da:

- V drugi točki nama obnašanje glede osebe in voda ustreza. Razlago lahko pove @kastelecn.
- V deveti točki je prav tako vredu tako kot je (razlaga @kastelecn).

**Comment by pdurcik** [comment]
Če je projekt pripravljen, bi prosil @jaanos, da dodaste povezavo na repozitorij predmeta.

**Comment by jaanos** [comment]
Ko se poskusim registrirati, aplikacija pravi, da še nisem vpisan in naj se obrnem na admina. Pričakoval bi sicer, da se morda uporabnik doda v bazo in ga mora administrator aktivirati, a ne vidim nobenih sprememb na bazi.

Opazil sem še, da tabeli `prostovoljec` in `udelezenec` nimata glavnega ključa - v obeh primerih naj glavni ključ seveda sestoji iz obeh stolpcev tabele.

Pripomnil pa bi še na zgornjo pripombo od @darkemy glede SQL injection. Če v poizvedbo vstavljate ime tabele ali stolpca, potem ne gre drugače, kot da se ga vstavi neposredno v niz (npr. s `%` ali `format` - sicer se bodo imena vnesla kot SQL-ovi nizi, kar bo povzročilo napako). Seveda pa tak način ni primeren za uporabo v končni aplikaciji - v `pomozne_funkcije.py`, ki ga sama poganjata za ustvarjanje baze in uvoz podatkov (ter imata tako boljši nadzor nad vhodom), pa je to sprejemljivo (podatke pa seveda vseeno podajajta kot drugi argument metode `execute`). Nekaj nevarnih poizvedb sicer še imata na koncu `uvoz_podatkov.py`.

**Comment by pdurcik** [comment]
Glede registracije je mišljeno, da se lahko registrirajo le tisti starši, ki so že dodani v bazo (torej tisti, od katerih podatke admin doda v bazo) (kot je opisano v `README.md`). V resničnem svetu bi torej admin moral dobiti 'na papirju' napisane podatke osebe, ki se želi registrirati, da jih vnese v bazo.

Kar ste zgoraj opisali bom popravil tekom dneva.

**Comment by pdurcik** [comment]
Sem popravil glavne ključe v `prostovoljec` in `udelezenec` ter popravil nevarne poizvedbe v `uvoz_podatkov.py`.

**Comment by jaanos** [comment]
Aha, sem spregledal, da imate podatke za prijavo v `README.md`. Glede na to, da aplikacija večinoma deluje, bom dodal povezavo na repozitorij predmeta, tako da se lahko z @alenFMF domenita za termin zagovora (če se še niste). Če bosta torej še kaj spreminjala, prosim javita, da posodobim povezavo.

Sicer pa je trenutno nekoliko nepregledno, saj imata vse na eni strani (ki se vsakič naloži na vrhu) - predvsem to velja za administratorski vmesnik. Ena možnost bi bila, da aplikacijo razbijeta na več strani, lahko pa enostavno poskrbita, da se po neki akciji na strani ta ponovno naloži na istem razdelku. V ta namen bo potrebno posodobiti polja `action` pri značkah `form`, npr.
```HTML
<form action="#išči" role="form" method="post" class="form">
```
Ko naredita zahtevek `POST` in se stanje v bazi spremeni, je potrebno narediti še `redirect` na ustrezno stran, da se pri osveževanju strani poizvedba ne naredi še enkrat. Tako imata lahko samo branje podatkov za izpis samo na enem mestu. Obvestilo o uspešni spremembi lahko potem posredujeta v `redirect`u, kjer povesta še, na kateri razdelek naj se stran premakne:
```python
        bottle.redirect('/indexadmin/?%s#%s' %
            (bottle.urlencode({'napaka6': 'Funkcija je bila uspešno spremenjena!'}),
             bottle.urlquote('člani')))
```
Seveda bo potrebno v `index_admin` še pridobiti ta obvestila za vstavljanje v predlogo, npr.
```python
napaka6 = bottle.request.GET.napaka6
```
